


[Random]
Seeded = True
Seed = 42

;Raw data
[Raw Data]
Folder = /mnt/x/School/trajects/raw_data/
; Pre-processing
[Data NPY]
Output Folder = /mnt/x/School/trajects/pre_processed_data_npy/
File Extension = npy


[Data Scrambling]
Output Folder = /mnt/x/School/trajects/pre_processed_data_scrambled/
File Extension = npy

; Data Embedding
[Data Embedding]
; input from scrambled data
Input folder = /mnt/x/School/trajects/pre_processed_data_scrambled/
Input Extension = npy
Output Folder = ./data/embedded/images/

batch size = 64
nr of workers = 16
image height = 166
image width = 166


; Training Parameters
[Model Training]
Dataset Folder = ./data/dataset/images/small/

Model Save Folder = ./models/cnn/


[Logging]
Enable Logging = True
Folder = ./logs/







