


[Random]
Seeded = True
Seed = 42

;Raw data
[Raw Data]
Folder = /mnt/x/School/trajects/raw_data/
; Pre-processing
[Data NPY]
Output Folder = /mnt/x/School/trajects/pre_processed_data_npy/
File Extension = npy


[Data Scrambling]
Output Folder = /mnt/x/School/trajects/pre_processed_data_scrambled/
File Extension = npy

; Data Embedding
[Data Embedding]
; input from scrambled data
Input folder = /mnt/x/School/trajects/pre_processed_data_scrambled/
Input Extension = npy
Output Folder = ./data/embedded/images/

batch size = 64
nr of workers = 16
image height = 166
image width = 166


[Data Splitting]
; 1% of data
Small Dataset Folder = ./data/dataset/images/small/full_dataset/
; 25% of data
Medium Dataset Folder = ./data/dataset/images/medium/full_dataset/
; 100% of data
Large Dataset Folder = ./data/dataset/images/large/full_dataset/
[Train Validation Test Split]
Input Folder = ./data/dataset/images/small/full_dataset/
Split Folder = ./data/dataset/images/small/
Train percent = 0.70
Test percent = 0.15
; Validation percent is inferred as the remainder

; Training Parameters
[Model Training]
; train/validation/test split folders
Model Save Folder = ./models/dcnn/
Input Folder = ./data/dataset/images/large/




[Logging]
Enable Logging = True
Folder = ./logs/







